#!groovy

// Generated by IBM TransformationAdvisor
// Fri Jun 28 12:34:48 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}